<?php

return [
    [
        'name' => 'merchant_id',
        'title' => '商户ID',
        'type' => 'string',
        'content' =>[],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '请输入商户ID',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'key',
        'title' => '商户密钥',
        'type' => 'string',
        'content' =>[],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '请输入商户密钥',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_id',
        'title' => '应用ID',
        'type' => 'string',
        'content' =>[],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '请输入应用ID',
        'ok' => '',
        'extend' => '',
    ],
    array(
        'name'    => 'rechargetips',
        'title'   => '充值提示文字',
        'type'    => 'text',
        'content' =>
            array(),
        'value'   => '余额可用于购买任意产品与服务',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'moneylist',
        'title'   => '充值金额列表',
        'type'    => 'array',
        'content' =>
            array(),
        'value'   =>
            array(
                '￥10'  => '10',
                '￥20'  => '20',
                '￥30'  => '30',
                '￥50'  => '50',
                '￥100' => '100',
            ),
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'defaultmoney',
        'title'   => '默认充值金额',
        'type'    => 'string',
        'content' =>
            array(),
        'value'   => '10',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'minmoney',
        'title'   => '最低充值金额',
        'type'    => 'string',
        'content' =>
            array(),
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '最低的充值金额',
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'iscustommoney',
        'title'   => '禁止手动输入金额',
        'type'    => 'radio',
        'content' =>
            array(
                1 => '开启',
                0 => '关闭',
            ),
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ),
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'array',
        'content' =>
            array(),
        'value' => '没有下面的资料请到荔枝付官网(<a href="https://lizhifu.net" target="_blank">https://lizhifu.net</a>)，3秒钟免费注册账号，30秒配置收款账号立即开始收款！',
        'rule' => '',
        'msg' => '',
        'tip' => '荔枝付参数配置',
        'ok' => '',
        'extend' => '',
    ]
];
